- name: check for the uptime
  shell: uptime | awk '{print $3}'
  register: uptime
  until: uptime.stdout == "3"
  retries: 100
  delay: 10

- name: show uptime
  debug:
    msg: "{{ uptime.stdout }}"

- name: expunge the instance
  cs_instance:
    name: "{{instance_state.display_name }}"
    state: expunged
  delegate_to: localhost
  register: instance_state

- debug:
    msg: "{{instance_state}}"

- name: capture relevant details
  set_fact:
    vm_id: "{{ instance_state.msg.id }}"
    vm_name: "{{ instance_state.msg.name }}"
    date_created: "{{ instance_state.msg.created }}"
    iaas_rate: 0.040622
    os: "CentOS 7.4"
    service_offering: "Standard 1 vCPU 2 GB RAM"
    iaas: "IaaS NO OS VM"
    disk_size: 10
    disk1: "Archive Data Volume (Tier 2)"
    disk2: ""
    archive_storage_rate: 0.000629 
    std_storage_rate: 0
    iops_5k_rate: 0
    iops_10k_rate: 0
    uptime: "{{ uptime.stdout }}"

- name: print 
  debug:
    msg: >
      "{{ vm_name }} 
      {{ vm_id }} 
      {{ date_created }} 
      {{ os }}
      {{ iaas }}
      {{ disk_size }}
      {{ disk1 }}
      {{ disk2 }}
      {{ service_offering }}
      {{ iaas_rate }}
      {{ archive_storage_rate }}
      {{ std_storage_rate }}
      {{ iops_5k_rate }}
      {{ iops_10k_rate }}
      {{ uptime }}"

























