jenkins:
  systemMessage: "This jenkins instance is for icdc program"
  agentProtocols:
    - "JNLP4-connect"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: jenkinsAdmin
          password: ${jenkinsAdmin}
        - id: vdonkor
          password: ${vdonkor}
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:authenticated"
        - "Job/Read:authenticated"
        - "View/Read:authenticated"
        - "Overall/Administer:authenticated"
  crumbIssuer: "standard"
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "tcp://${DOCKER_AGENT_IP}:2375"
        templates:
          - labelString: "icdc_maven"
            dockerTemplateBase:
              image: "vdonkor/cicd-maven"
              environmentsString: |
                TOMCAT_IP=${TOMCAT_IP}
            remoteFs: "/home/jenkins"
            connector:
              attach:
                user: "root"
            instanceCapStr: "10"
jobs:
  - script: >
      folder('icdc')
  - url: https://raw.githubusercontent.com/gklu/devops/master/jobs/icdc/pipeline.groovy
tool:
  git:
    installations:
      - name: Default
        home: git
  jdk:
    installations:
      - name: jdk11
        home: /usr/lib/jvm/jre-11-openjdk
  maven:
    installations:
      - name: maven-3.6.1
        home: /usr/local/maven
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: icdc-jenkin-slack
              secret: "${SLACK_TOKEN}"
              description: send slack notification
          - usernamePassword:
              scope: GLOBAL
              id: c9c-deployer
              username: "icdcTomcat"
              password: ${jenkinsAdmin}
              description: user for deploying c9c

unclassified:
  slackNotifier:
    teamDomain: ${SLACK_TEAM} # i.e. your-company (just the workspace name not the full url)
    tokenCredentialId: icdc-jenkin-slack
  