---
# defaults file for rubrik
credentials:
  node_ip: 10.10.10.10
  api_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzZGY0ZDRlMi1lMjI4LTRhNDktODYwYi1mNjQ3YzNhN2FmYzIiLCJpc3MiOiJkMTFiZTM1OC1jYjMxLTQyMDYtYmYxMy1lNDRjNzRjOTM2MWEiLCJqdGkiOiI2ZWJiODlhYy1kZDA3LTQ0MjItYjVlNC04YWEyOGRjZWY4NjEifQ.6qlT164OldfozHivE8U6oCkYvoJIFHeksi4Yyf_e3ws

