- name: clean data volumes
  delegate_to: localhost
  block:
    - name: list all data volumes
      shell: cs listVolumes | jq -r .volume[].id
      register: volumes

    - name: show the volume(s) to be deleted
      debug:
        msg: "{{volumes.stdout}}"

    - name: delete all data volumes
      shell: cs deleteVolume id={{ item }}
      loop:
        - "{{ volumes.stdout }}"
      when: volumes.stdout != ""
      register: volumes_deleted

    - name: show deleted volumes
      debug:
        msg: "{{ volumes_deleted }}"