- name: clean data volumes
  delegate_to: localhost
  block:
    - name: list all data volumes
      shell: cs listVolumes | jq -r .volume[].name
      register: volumes

    - name: show the volume(s) to be deleted
      debug:
        #msg: "{{ volumes|map(attribute='stdout_lines')|list }}"
        msg: "{{ volumes }}"

    # - name: delete all data volumes
    #   cs_volume:
    #     name: "{{ item }}"
    #     state: absent
    #     poll_async: yes
    #   loop:
    #     - "{{ volumes.stdout }}"
    #   when: volumes.stdout != ""
    #   register: volumes_deleted

    # - name: show the volume(s) to be deleted
    #   debug:
    #     msg: "{{ volumes_deleted }}"