- name: open http and https services
  firewalld:
    service: "{{item}}"
    zone: public
    immediate: yes
    permanent: yes
    state: enabled
  loop:
    - http
    - https
- name: create jenkins group
  group:
    name: jenkins
    gid: 1000
    state: present

- name: create jenkins user
  user:
    name: jenkins
    uid: 1000
    group: jenkins

- name: create file structure for the jenkins
  file:
    path: "{{ jenkins_home }}"
    state: directory
    group: jenkins
    owner: jenkins

- name: copy docker files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: jenkins
    owner: jenkins
  with_items:
    - {src: 'docker-compose.yml.j2',dest: '{{jenkins_home}}/docker-compose.yml'}
    - {src: 'dockerfile_jenkins.j2',dest: '{{jenkins_home}}/dockerfile_jenkins'}
    - {src: 'plugins.txt.j2',dest: '{{jenkins_home}}/plugins.txt'}

- name: build the docker image
  docker_image:
    path: "{{ jenkins_home }}"
    name: imt/jenkins
    dockerfile: "{{ dockerfile }}"
    state: present

- name: create jenkinsAdmin secret
  file:
    path: "{{ jenkins_home }}/jenkinsAdmin"
    owner: jenkins
    group: jenkins
    state: touch

- name: update jenkinsAdmin with pass
  lineinfile:
    path: "{{ jenkins_home }}/jenkinsAdmin"
    line: "{{ jenkinsAdmin }}"

- name: start the jenkins
  docker_service:
    project_src: "{{ jenkins_home }}"
    state: present

# - name: Init a new swarm with default parameters
#   docker_swarm:
#     state: present

# - name: check if secret is already created
#   shell: docker secret ls -f name=jenkinsAdmin | wc -l
#   register: output_secret

# - debug:
#     msg: "{{ output_secret.stdout }}"  

# - name: set docker secret user
#   shell: echo {{ jenkinsAdmin }} | docker secret create jenkinsAdmin -
#   when: output_secret.stdout == "1"
#   register: output

# - name: deploy jenkins
#   command:  docker stack deploy --compose-file {{ docker_compose_file }} jenkins
#   register: output

# - debug:
#     msg: "{{output.stdout }}"


