//load shared library for slack notification
//@Library('shared-library')_

//map slack colors to build result
def BUILD_COLORS = ['SUCCESS': 'good', 'FAILURE': 'danger', 'UNSTABLE': 'danger', 'ABORTED': 'danger']

//extract user from build info
def getUser() {
    return currentBuild.rawBuild.getCause(Cause.UserIdCause).getUserId()
}

pipeline {
  environment {
    BUILD_USER = ''
  }
  agent {
    node {
      label 'icdc_maven'
    }
  }
  options {
    timestamps()
  }
  tools { 
    maven 'maven-3.6.1' 
    jdk 'jdk11' 
  }
  stages {
    stage('Checkout') {
      steps {
        git branch: 'master',
            url: 'https://github.com/jonkiky/neo4j_for_testing.git'
      }
    }
    stage('Build') {
      environment {
        TOMCAT_IP = "${TOMCAT_IP}"
      }
      steps {
        sh "mvn package"
        sh "mv target/RESTFfullDemo-0.0.1-SNAPSHOT.war target/RESTFfullDemo.war"
      }
    }
    stage('Deploy') {
      when {
        expression {
          currentBuild.result == null || currentBuild.result == 'SUCCESS' 
        }
      }
      steps {
        ansiColor('xterm') {
          withCredentials([usernameColonPassword(credentialsId: 'c9c-deployer', variable: 'DEPLOYER')]) {
            sh 'cd target && curl -T RESTFfullDemo.war http://$DEPLOYER@$TOMCAT_IP/manager/text/deploy?path=/RESTFfullDemo&update=true'
          }
        }
      }
    }
  }
  post {
    always {
      //slackSend(channel: '#random', message: 'My first Jenkins build')
      //sh 'echo "Your application is deployed to http://k9dc.essential-dev.com/RESTFfullDemo"'
      script {
        BUILD_USER = getUser()
      }
      sh '''
            curl -H 'Content-type: application/json' -X POST --data-urlencode -d 
            "payload='{
                "attachments": [
                    {
                        "fallback": "ICDC Jenkins Build",
                        "color": "BUILD_COLORS[currentBuild.currentResult]",
                        "author_name": "Jenkins",
                        "title": "${currentBuild.currentResult}",
                        "text": "Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} by ${BUILD_USER}\n Details at: ${env.BUILD_URL}",
                        "footer": "icdc devops",
                    }
                ]
              }'" https://hooks.slack.com/services/
    }
  }
}