pipeline {
  agent {
    node {
      label 'icdc_maven'
    }
  }
  options {
    timestamps()
  }
  tools { 
    maven 'maven-3.6.1' 
    jdk 'jdk11' 
  }
  stages {
    stage('Checkout') {
      steps {
        git branch: 'master',
            url: 'https://github.com/jonkiky/neo4j_for_testing.git'
      }
    }
    stage('Build') {
      environment {
        TOMCAT_IP = "${TOMCAT_IP}"
      }
      steps {
        sh "mvn package"
        sh "mv target/RESTFfullDemo-0.0.1-SNAPSHOT.war target/RESTFfullDemo.war"
      }
    }
    stage('Deploy') {
      when {
        expression {
          currentBuild.result == null || currentBuild.result == 'SUCCESS' 
        }
      }
      steps {
        ansiColor('xterm') {
          withCredentials([usernameColonPassword(credentialsId: 'c9c-deployer', variable: 'DEPLOYER')]) {
            sh 'cd target && curl -T RESTFfullDemo.war http://$DEPLOYER@$TOMCAT_IP/manager/text/deploy?path=/RESTFfullDemo&update=true'
          }
        }
      }
    }
  }
  post {
    always {
      slackSend(channel: '#random', message: 'My first Jenkins build')
      sh 'echo "Your application is deployed to http://k9dc.essential-dev.com/RESTFfullDemo"'
    }
  }
}