- name: setup ssh key
  cs_sshkeypair:
    name: bill-ssh-key
    public_key: "{{ lookup('file', './.ssh/id_rsa.pub') }}"
  delegate_to: localhost

- name: lunch daily centos 6 vm
  cs_instance:
    name: centos6-bill
    display_name: centos6-bill
    template: centos65_x86_64
    service_offering: t2.micro
    network: app
    ssh_key: bill-ssh-key
    disk_offering: Small
    state: started
    tags:
      - key: purpose
        value: billing
  delegate_to: localhost
  register: instance_state

- debug:
    msg: "{{ instance_state }}"

- name: enable static NATs
  cs_staticnat: vm="{{ inventory_hostname_short }}" ip_address="{{ public_ip }}"
  when: public_ip is defined

