- name: list all running instances
  command: cs listVirtualMachines state=Running
  register: running_vm

- name: get the facts about the running vm if any
  set_fact :
    vm_facts: "{{ running_vm.stdout|from_json }}"
   

- name: get the tag key is should be purpose
  set_fact :
    vm_key: "{{ vm_facts.virtualmachine | json_query('[*].tags[*].value') | flatten}}"
    vm_name: "{{ vm_facts.virtualmachine | json_query('[*].name')}}"

- name: show running vm
  debug: 
    msg: "{{ vm_name }}"

- name: ensure the instance is destroyed.
  cs_instance:
    name: "{{ item }}"
    state: expunged
  delegate_to: localhost
  with_items:
    - "{{ vm_name }}"
  when: '"billing" in vm_key' 