
- name: lunch daily windows 2012 vm
  delegate_to: localhost
  block:
    - name: lunch windows 2012
      cs_instance:
        name: "{{ inventory_hostname_short }}"
        display_name: "{{ inventory_hostname_short }}"
        template: windows-2012-billing
        service_offering: "Standard 1 vCPU 2 GB RAM"
        network: DemoWebtier
        disk_offering: "High IOPS SSD - 5K"
        disk_size: 10
        state: started
        tags:
          - key: purpose
            value: billing
      register: instance_state

    - debug:
        msg: "{{ instance_state.state }}"

    - name: enable static NATs
      cs_staticnat: 
        vm: "{{ inventory_hostname_short }}" 
        ip_address: "{{ public_ip }}"
        vpc: DemoVPC
        network: DemoWebtier
      when: public_ip is defined
      register: nat_state

    - debug:
        msg: "{{ nat_state }}"

    - name: attach volume to instance windows 2012
      cs_volume:
        name: disk2
        disk_offering: "High IOPS SSD - 10K"
        size: 10
        vm: "{{ inventory_hostname_short }}"
        state: present
      register: myoutput  

    - debug:
        msg: "{{myoutput}}"

- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900
  
 

 

