
- name: check uptime
  win_shell: |
      function Get-Uptime {
      $os = Get-WmiObject win32_operatingsystem
      $uptime = (Get-Date) - ($os.ConvertToDateTime($os.lastbootuptime))
      $Display = "Uptime: " + $Uptime.Days + " days, " + $Uptime.Hours + " hours, " + $Uptime.Minutes + " minutes" 
      Write-Output $Display
      }
      Get-Uptime
  register: myuptime


- name: print out the output
  debug: 
    msg: "{{ myuptime.stdout }}"


  

 

