- name: lunch daily centos 7.4 vm
  cs_instance:
    name: "{{ inventory_hostname_short }}" 
    display_name: "{{ inventory_hostname_short }}"
    template:   centos-7-billing
    service_offering: "Standard 1 vCPU 2 GB RAM"
    network: validator
    #ssh_key: mykey
    disk_offering: "Archive Data Volume"
    state: started
    user_data: |
        #cloud-config
        ssh_pwauth: yes
    tags:
      - key: purpose
        value: billing
  delegate_to: localhost
  register: instance_state

- debug:
    msg: "{{ instance_state.state }}"

- name: enable static NATs
  cs_staticnat: 
    vm: "{{ inventory_hostname_short }}" 
    ip_address: "{{ public_ip }}"
    vpc: BillingVPC
    network: validator
  when: public_ip is defined
  delegate_to: localhost
  register: nat_state

- debug:
    msg: "{{ nat_state }}"

- name: Wait for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
  vars:
    ansible_connection: local




