version: '3.1'
 
services:
 
  main:
    image: milcloud/jenkins
    ports:
      - 80:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-password
    restart: always
    volumes:
      - /local/jenkins:/var/jenkins_home
 
secrets:
  jenkins-user:
    external: true
  jenkins-password:
    external: true
