- name: check for the uptime
  shell: uptime | awk '{print $3}'
  register: uptime
  until: uptime.stdout == "5"
  retries: 100
  delay: 10

- name: show uptime
  debug:
    msg: "{{ uptime.stdout }}"

- name: expunge the instance
  cs_instance:
    name: "{{instance_state.display_name }}"
    state: expunged
  delegate_to: localhost
  register: instance_state

- debug:
    msg: "{{instance_state}}"

- name: capture relevant details
  set_fact:
    vm_id: "{{ instance_state.id }}"
    vm_name: "{{ instance_state.name }}"
    date_created: "{{ instance_state.created }}"
    iaas_rate: 0.040622
    os: "CentOS 7.4"
    service_offering: "Standard 1 vCPU 2 GB RAM"
    iaas: "IaaS NO OS VM"
    disk_size: 10
    disk1: "Archive Data Volume (Tier 2)"
    disk2: "n/a"
    archive_storage_rate: 0.000629 
    std_storage_rate: 0
    iops_5k_rate: 0
    iops_10k_rate: 0
    uptime: "{{ uptime.stdout }}"

- name: perform database operations
  delegate_to: localhost
  block:
    - name: create mysql statement
      shell: >
        echo "insert into billing
        (
        vm_name,
        vm_id,
        date_created,
        os,
        iaas,
        disk_size,
        disk1,
        disk2,
        service_offering,
        iaas_rate,
        archive_storage_rate,
        std_storage_rate,
        iops_5k_rate,
        iops_10k_rate,
        uptime
        ) values(
        '{{ vm_name }}',
        '{{ vm_id }}',
        '{{ date_created }}',
        '{{ os }}',
        '{{ iaas }}',
        {{ disk_size }},
        '{{ disk1 }}',
        '{{ disk2 }}',
        '{{ service_offering }}',
        {{ iaas_rate }},
        {{ archive_storage_rate }},
        {{ std_storage_rate }},
        {{ iops_5k_rate }},
        {{ iops_10k_rate }},
        {{ uptime }});" > billing.sql

    - name: import billing data
      mysql_db:
        state: import
        name: "{{ db_name }}"
        target: billing.sql
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"

























