---
- name: bill validator
  hosts: "{{ host_a  }}"
  connection: local

  roles:
    - configure_cloudstack_credentials
    - create-instance

- name: bill validator
  hosts: "{{ host_b }}"
  gather_facts: no

  roles:
    - expunge-instance

    