---
- name: setup jenkins server
  hosts: "{{ host  }}"
  become: yes
  become_user: root
  become_method: sudo
  #user: vdonkor

  roles:
    # #- create_sftp_users
    # # - setup-jenkins
    # - setup-gitlab
    - setup-zabbix