# ---
- name: bill validator
  hosts: "{{ host  }}"
  gather_facts: no
  connection: local

  roles:
    - create-rhel-instance

- name: bill validator
  hosts: "{{ host  }}"
  gather_facts: no
 
  roles:
    - expunge-rhel-instance

    