- name: list virtual machines
  command: cs listVirtualMachines
  register: output

- name: print the output
  debug:
    msg: "{{ output }}"

- name: list templates
  command: cs listTemplates templatefilter=featured
  register: output

- name: print the output
  debug:
    msg: "{{ output }}"

- name: gather instance facts
  cs_instance_facts:
    name: DemoVM
  # delegate_to: localhost
  register: vm

- debug:
    var: cloudstack_instance

- debug:
    var: vm
