# - name: list virtual machines
#   shell: cs listVirtualMachines
#   register: output

# - name: print the output
#   debug:
#     msg: "{{ output.stdout }}"

- name: gather instance facts
  cs_instance_facts:
    name: DemoVM
  delegate_to: localhost
  register: vm

- debug:
    var: cloudstack_instance

- debug:
    var: vm